name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./api
        run: |
          python -m pytest tests/

      - name: Build Docker Image
        run: |
          docker compose build

      - name: Authenticate with AWS ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin ECR_URL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      - name: Tag and Push Docker Image to ECR
        run: |
          docker tag drones-demo-app:latest ECR_URL/drones-demo-app:latest
          docker push ECR_URL/drones-demo-app:latest

      - name: Clean Up
        run: |
          docker logout ECR_URL
        id: cleanup
        if: always()
  
      - name: Notify Status
        if: always()
        run: echo "Workflow completed"